# Generated by Django 4.1.6 on 2023-02-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
