# Generated by Django 4.1.6 on 2023-03-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_userbookrelation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
