# Generated by Django 4.1.6 on 2023-03-06 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_comments_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 17, 20, 54, 318937, tzinfo=datetime.timezone.utc)),
        ),
    ]
