# Generated by Django 4.1.6 on 2023-03-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_comments_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text_comment',
            field=models.TextField(null=True),
        ),
    ]
