# Generated by Django 4.1.6 on 2023-03-09 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0016_alter_comments_text_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='commentators',
            field=models.ManyToManyField(related_name='book_comment', through='store.Comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
